Traceback (most recent call last):
  File "/home/kballou/.local/bin/mpi_run.py", line 17, in <module>
    err = subprocess.call(mpi_cmd)
  File "/usr/lib/python3.3/subprocess.py", line 522, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.3/subprocess.py", line 1528, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.3/subprocess.py", line 1485, in _try_wait
    (pid, sts) = _eintr_retry_call(os.waitpid, self.pid, wait_flags)
  File "/usr/lib/python3.3/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Command exited with non-zero status 1
0.07user 0.00system 0:00.32elapsed 25%CPU (0avgtext+0avgdata 6836maxresident)k
2536inputs+8outputs (56major+4207minor)pagefaults 0swaps
